frase = ('Curso em vídeo')
print(frase)
print("""bla bla bla bla bla bla bla bla bla bla""" )
print(frase.count('o'))
print(len(frase))
print(frase.upper().count('v'))
print(frase.strip)
frase = frase.replace('Curso', 'urso')
print(frase.find('vídeo'))
print(frase.split())